name: CI/CD Pipeline 
on:
  push: 
    branches: - main 
jobs: 
  build-deploy: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Clonar el repositorio 
      uses: actions/checkout@v3
    - name: Configurar Google Cloud SDK 
      uses: google-github-actions/setup-gcloud@v1
      with: 
        project_id: ${{ secrets.GCP_PROJECT }} 
        service_account_key: ${{secrets.GCP_SA_KEY }} 
    - name: Autenticar Docker con Artifact Registry 
      run: |
      gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: Construir y enviar la imagen a Artifact Registry 
      run: |
      docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mi-repo/mi-app .
      docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mi-repo/mi-app   
    - name: Desplegar en Cloud Run 
      run: |
      gcloud run deploy mi-app \
        --image us-central1- docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mi-repo/mi-app \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated